// Reducer auth
export const AUTH_LOGIN = 'AUTH_LOGIN';
export const AUTH_REGISTER = 'AUTH_REGISTER';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const GET_CURRENT_USER = 'GET_CURRENT_USER';
export const UPDATE_CURRENT_USER = 'UPDATE_CURRENT_USER';
export const ADD_ADDRESS_USER = 'ADD_ADDRESS_USER';

// Reducer user
export const GET_ALL_USER = 'GET_ALL_USER';

// Reducer service
export const CREATE_SERVICE = 'CREATE_SERVICE';
export const UPDATE_SERVICE = 'UPDATE_SERVICE';
export const GET_SERVICES_BY_USER = 'GET_SERVICES_BY_USER';

// Reducer proveedorService
export const CREATE_PROVEEDORSERVICE = 'CREATE_PROVEEDORSERVICE';
export const GET_PROVEEDORSERVICES_BY_ESTADO =
  'GET_PROVEEDORSERVICES_BY_ESTADO';
